<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MehrIt\OttoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MehrIt\OttoApiClient;

use MehrIt\OttoApiClient\Configuration;
use MehrIt\OttoApiClient\ApiException;
use MehrIt\OttoApiClient\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MehrIt\OttoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrUpdateProductVariations
     *
     * Create or update your product variations and get a process-id to query results. The limit for the number of product variations in one request is 500..
     *
     */
    public function testCreateOrUpdateProductVariations()
    {
    }

    /**
     * Test case for getPartnerProducts
     *
     * Read your product variations. The total number of results could be limited by specifying query parameters. Generally the resulting product variations will be paginated. The default page length is 100 product variations per response, also the page size limit. The links specified in the result can be used to page through the total result space..
     *
     */
    public function testGetPartnerProducts()
    {
    }

    /**
     * Test case for getProductVariation
     *
     * Read a single product variation..
     *
     */
    public function testGetProductVariation()
    {
    }
}
