<?php
/**
 * ProductOnlineStatusApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MehrIt\OttoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MehrIt\OttoApiClient;

use MehrIt\OttoApiClient\Configuration;
use MehrIt\OttoApiClient\ApiException;
use MehrIt\OttoApiClient\ObjectSerializer;

/**
 * ProductOnlineStatusApiTest Class Doc Comment
 *
 * @category Class
 * @package  MehrIt\OttoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductOnlineStatusApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getOnlineStatus
     *
     * DEPRECATED - please use the corresponding active-status endpoint instead..
     *
     */
    public function testGetOnlineStatus()
    {
    }

    /**
     * Test case for getVariationOnlineStatus
     *
     * DEPRECATED - please use the corresponding active-status endpoint instead..
     *
     */
    public function testGetVariationOnlineStatus()
    {
    }

    /**
     * Test case for updateOnlineStatus
     *
     * DEPRECATED - please use the corresponding active-status endpoint instead..
     *
     */
    public function testUpdateOnlineStatus()
    {
    }
}
